CREATE TABLE [dbo].[Customers]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(), 
    [Name] VARCHAR(100) NULL, 
    [Email] VARCHAR(100) NULL, 
    [BirthDate] DATETIME NULL
)
