CREATE TABLE [dbo].[EntryLog]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[ProjectId] UNIQUEIDENTIFIER NOT NULL,
	[EntryDate] DATETIME NOT NULL,
	[Hours] DECIMAL(10, 2) NOT NULL,
	[Description] VARCHAR(250)
)
